const data = [
  {
    id: "1",
    title: "Blogbook.tech",
    category: "websites",
    image: "img/project.jpg",
    ss: "img/project.jpg",
    brief: "Bloggig Website CMS project",
    about: `It is my first big project. It is generally a blogging website where ANYONE can read or write blog posts of different categories in a single place.`,
    date: "Nov 2020 - Present",
    tools: "PHP, Html, CSS, javascript",
    link: "https://blogbook.tech",
    visible: "show"
  },
  {
    id: "2",
    title: "Covay.in",
    category: "websites",
    image: "img/project.jpg",
    ss: "img/project.jpg",
    brief: "Team Project ",
    about: `Worked as a front end web devloper for covay. It is developed by our team from IEM only. The objective of the website is to provide confirmed oxygen cylinders sources during the oxygen crysis.`,
    date: "Feb 2021- May 2021",
    tools: "html/css python(django",
    link: "www.covay.in",
    visible: "show"
  },
  {
    id: "3",
    title: "Incognito",
    category: "websites",
    image: "img/project.jpg",
    ss: "img/project.jpg",
    brief: "Entreprenuership Website",
    about: `It is website for our practice venture for Entreprenuership. It helps to connect teachers and students for a local home to home tuitions`,
    date: "March 2021",
    tools: "Bootstrap Html CSS",
    link: "https://blogbook.epizy.com/incognito/",
    visible: "show"
  },
  {
    id: "4",
    title: "Portfolio",
    category: "websites",
    image: "img/project.jpg",
    ss: "img/project.jpg",
    brief: "Own Portfolio",
    about: `This is the portfolio website which is a type of project of its owm. `,
    date: "Aug-2021",
    tools: "Html CSS javascript",
    link: "www.chaitakgorai.me",
    visible: "show"
  },
  {
    id: "5",
    title: "S4DS-IEM",
    category: "club",
    image: "img/project.jpg",
    ss: "img/project.jpg",
    brief: "S4DS-IEM website",
    about: `Worked for the S4DS-IEM chapter to develop its website. `,
    date: "Aug-2021",
    tools: "Bootstrap Html/Css",
    link: "s4ds-iem.github.io/s4ds-iem-website/",
    visible: "show"
  },
  {
    id: "6",
    title: "ICCAES 2021",
    category: "club",
    image: "img/project.jpg",
    ss: "img/project.jpg",
    brief: "ICCAES 2021 Website",
    about: `Worked as web developer for the organising team to update the website`,
    date: "Aug-2021",
    tools: "Html/css Bootstrap",
    link: "Https://chaitakgorai.me/ICCAES2021/index.html",
    visible: "show"
  },
  {
    id: "7",
    title: "Wheather App",
    category: "js-app",
    image: "img/project.jpg",
    ss: "img/project.jpg",
    brief: "Weather API project",
    about: `It is a REALTIME wheather api project whic shows wheather of any particular place.`,
    date: "June 2021",
    tools: "Javascript API",
    link: "http://blogbooks.epizy.com/weather/",
    visible: "show"
  },
  {
    id: "8",
    title: "GitHub Finder App",
    category: "js-app",
    image: "img/project.jpg",
    ss: "img/project.jpg",
    brief: "Github Finder",
    about: `Find any github acount details by searching with username.`,
    date: "June 2021",
    tools: "Javascript API",
    link: "https://blogbook.epizy.com/github_finder",
    visible: "show"
  },
  {
    id: "9",
    title: "Jokes App",
    category: "js-app",
    image: "img/project.jpg",
    ss: "img/project.jpg",
    brief: "Jokes",
    about: `Read jokes`,
    date: "May 2021",
    tools: "Javascript API",
    link: "http://blogbooks.epizy.com/jokes_generator/",
    visible: "show"
  },
  {
    id: "10",
    title: "BookList App",
    category: "js-app",
    image: "img/project.jpg",
    ss: "img/project.jpg",
    brief: "BookList App",
    about: `List any number of books by their name.`,
    date: "June 2021",
    tools: "Javascript API",
    link: "https://chaitak-gorai.github.io/learning_javascript/booklist/",
    visible: "show"
  },
  {
    id: "11",
    title: "Loan Calculator App",
    category: "js-app",
    image: "img/project.jpg",
    ss: "img/project.jpg",
    brief: "Loan Calculator App",
    about: `Calculate loan of any amount with intrest, time values`,
    date: "June 2021",
    tools: "Javascript API",
    link: "https://chaitak-gorai.github.io/learning_javascript/loan_calculator/",
    visible: "show"
  },
  {
    id: "12",
    title: "Number Guesser App",
    category: "js-app",
    image: "img/project.jpg",
    ss: "img/project.jpg",
    brief: "Number Guesser App",
    about: `Find your luck by playing the number guesser game`,
    date: "June 2021",
    tools: "Javascript API",
    link: "https://chaitak-gorai.github.io/learning_javascript/num_guesser/",
    visible: "show"
  },
  {
    id: "13",
    title: "Tasklist App",
    category: "js-app",
    image: "img/project.jpg",
    ss: "img/project.jpg",
    brief: "Tasklist App",
    about: `Add tasks to the list`,
    date: "June 2021",
    tools: "Javascript API",
    link: "https://chaitak-gorai.github.io/learning_javascript/tasklist/",
    visible: "show"
  },

  {
    id: "100",
    title: "Blurry Loading",
    category: "js-mini",
    image: "img/project.jpg",
    ss: "img/project.jpg",
    brief: "Blurry Loading",
    about: `Blurry Loading`,
    date: "July 2021",
    tools: "Javascript ",
    link: "http://chaitakgorai.me/javascript_projects/Blurry_loading",
    visible: "show"
  },

  {
    id: "101",
    title: "Expanding Cards",
    category: "js-mini",
    image: "img/project.jpg",
    ss: "img/project.jpg",
    brief: "Expanding Cards",
    about: `BExpanding Cards`,
    date: "July 2021",
    tools: "Javascript ",
    link: "http://chaitakgorai.me/javascript_projects/Expanding_Cards",
    visible: "show"
  },
  {
    id: "102",
    title: "Hidden Search",
    category: "js-mini",
    image: "img/project.jpg",
    ss: "img/project.jpg",
    brief: "Hidden Search",
    about: `Hidden Search`,
    date: "July 2021",
    tools: "Javascript ",
    link: "http://chaitakgorai.me/javascript_projects/Hidden_Search",
    visible: "show"
  },
  {
    id: "103",
    title: "Progress Checker",
    category: "js-mini",
    image: "img/project.jpg",
    ss: "img/project.jpg",
    brief: "Progress Checker",
    about: `Progress Checker`,
    date: "July 2021",
    tools: "Javascript ",
    link: "http://chaitakgorai.me/javascript_projects/Progress_checker",
    visible: "show"
  },
  {
    id: "104",
    title: "Rotating Nav",
    category: "js-mini",
    image: "img/project.jpg",
    ss: "img/project.jpg",
    brief: "Rotating Nav",
    about: `Rotating Nav`,
    date: "July 2021",
    tools: "Javascript ",
    link: "http://chaitakgorai.me/javascript_projects/Rotating_nav",
    visible: "show"
  },
  {
    id: "105",
    title: "Scroll Animation",
    category: "js-mini",
    image: "img/project.jpg",
    ss: "img/project.jpg",
    brief: "Scroll Animation",
    about: `Scroll Animation`,
    date: "July 2021",
    tools: "Javascript ",
    link: "http://chaitakgorai.me/javascript_projects/Scroll_animation",
    visible: "show"
  }
];
